<?php

// DO NOT EDIT THIS FILE - IT IS GENERATED BY constant_generator.php

namespace donatj\UserAgent;

interface Bots {

	const ADKERNELTOPICCRAWLER  = 'AdkernelTopicCrawler';
	const AHREFSBOT             = 'AhrefsBot';
	const AHREFSSITEAUDIT       = 'AhrefsSiteAudit';
	const AMAZONADBOT           = 'AmazonAdBot';
	const AMAZONBOT             = 'Amazonbot';
	const ARCHIVE_ORG_BOT       = 'archive.org_bot';
	const AWARIOBOT             = 'AwarioBot';
	const BAIDUSPIDER           = 'Baiduspider';
	const BAIDUSPIDER_RENDER    = 'Baiduspider-render';
	const BARKROWLER            = 'Barkrowler';
	const BLEXBOT               = 'BLEXBot';
	const BRAVEBOT              = 'Bravebot';
	const CENSYSINSPECT         = 'CensysInspect';
	const CLAUDEBOT             = 'ClaudeBot';
	const COCCOCBOT_IMAGE       = 'coccocbot-image';
	const COCCOCBOT_WEB         = 'coccocbot-web';
	const CURL                  = 'curl';
	const DATAFORSEOBOT         = 'DataForSeoBot';
	const DISCORDBOT            = 'Discordbot';
	const DOTBOT                = 'DotBot';
	const DVBOT                 = 'DVbot';
	const EV_CRAWLER            = 'ev-crawler';
	const FEEDBOT               = 'feedbot';
	const GOOGLE_READ_ALOUD     = 'Google-Read-Aloud';
	const GOOGLE_SAFETY         = 'Google-Safety';
	const HEEXYBOT              = 'Heexybot';
	const IBOUBOT               = 'IbouBot';
	const LEIKIBOT              = 'Leikibot';
	const MINIFLUX              = 'Miniflux';
	const MODATSCANNER          = 'ModatScanner';
	const MOJEEKBOT             = 'MojeekBot';
	const MSNBOT_MEDIA          = 'msnbot-media';
	const OAI_SEARCHBOT         = 'OAI-SearchBot';
	const PERPLEXITYBOT         = 'PerplexityBot';
	const PERPLEXITY_USER       = 'Perplexity-User';
	const PETALBOT              = 'PetalBot';
	const PINTERESTBOT          = 'Pinterestbot';
	const PROXIMIC              = 'proximic';
	const SCOURRSSBOT           = 'ScourRSSBot';
	const SEMRUSHBOT            = 'SemrushBot';
	const SEMRUSHBOT_SI         = 'SemrushBot-SI';
	const SERANKINGBACKLINKSBOT = 'SERankingBacklinksBot';
	const SEZNAMBOT             = 'SeznamBot';
	const SLACKBOT              = 'Slackbot';
	const SMTBOT                = 'SMTBot';
	const SPIDERLING            = 'SpiderLing';
	const SURDOTLYBOT           = 'SurdotlyBot';
	const WELLKNOWNBOT          = 'WellKnownBot';
	const WPBOT                 = 'wpbot';
	const YANDEXIMAGES          = 'YandexImages';
	const YANDEXMOBILEBOT       = 'YandexMobileBot';
	const YANDEXRCA             = 'YandexRCA';
	const YANDEXUSERPROXY       = 'YandexUserproxy';

}

