<?php

// DO NOT EDIT THIS FILE - IT IS GENERATED BY constant_generator.php

namespace donatj\UserAgent;

interface Bots {

	public const ADKERNELTOPICCRAWLER  = 'AdkernelTopicCrawler';
	public const ADSBOT_GOOGLE         = 'AdsBot-Google';
	public const AHREFSBOT             = 'AhrefsBot';
	public const AHREFSSITEAUDIT       = 'AhrefsSiteAudit';
	public const AMAZONADBOT           = 'AmazonAdBot';
	public const AMAZONBOT             = 'Amazonbot';
	public const APPLEBOT              = 'Applebot';
	public const ARCHIVE_ORG_BOT       = 'archive.org_bot';
	public const AWARIOBOT             = 'AwarioBot';
	public const BAIDUSPIDER           = 'Baiduspider';
	public const BAIDUSPIDER_RENDER    = 'Baiduspider-render';
	public const BARKROWLER            = 'Barkrowler';
	public const BINGBOT               = 'bingbot';
	public const BLEXBOT               = 'BLEXBot';
	public const BRAVEBOT              = 'Bravebot';
	public const CENSYSINSPECT         = 'CensysInspect';
	public const CHATGPT_USER          = 'ChatGPT-User';
	public const CLAUDEBOT             = 'ClaudeBot';
	public const COCCOCBOT_IMAGE       = 'coccocbot-image';
	public const COCCOCBOT_WEB         = 'coccocbot-web';
	public const CURL                  = 'curl';
	public const DATAFORSEOBOT         = 'DataForSeoBot';
	public const DISCORDBOT            = 'Discordbot';
	public const DOTBOT                = 'DotBot';
	public const DVBOT                 = 'DVbot';
	public const EV_CRAWLER            = 'ev-crawler';
	public const FACEBOOKEXTERNALHIT   = 'facebookexternalhit';
	public const FEEDBOT               = 'feedbot';
	public const FEEDVALIDATOR         = 'FeedValidator';
	public const GOOGLEBOT             = 'Googlebot';
	public const GOOGLEBOT_IMAGE       = 'Googlebot-Image';
	public const GOOGLEBOT_VIDEO       = 'Googlebot-Video';
	public const GOOGLE_READ_ALOUD     = 'Google-Read-Aloud';
	public const GOOGLE_SAFETY         = 'Google-Safety';
	public const GPTBOT                = 'GPTBot';
	public const HEEXYBOT              = 'Heexybot';
	public const HUBSPOT_DOMAIN_CHECK  = 'HubSpot Domain check';
	public const IBOUBOT               = 'IbouBot';
	public const IMESSAGEBOT           = 'iMessageBot';
	public const LEIKIBOT              = 'Leikibot';
	public const MASTODON              = 'Mastodon';
	public const MINIFLUX              = 'Miniflux';
	public const MODATSCANNER          = 'ModatScanner';
	public const MOJEEKBOT             = 'MojeekBot';
	public const MSNBOT_MEDIA          = 'msnbot-media';
	public const OAI_SEARCHBOT         = 'OAI-SearchBot';
	public const PERPLEXITYBOT         = 'PerplexityBot';
	public const PERPLEXITY_USER       = 'Perplexity-User';
	public const PETALBOT              = 'PetalBot';
	public const PINTERESTBOT          = 'Pinterestbot';
	public const PROXIMIC              = 'proximic';
	public const SCOURRSSBOT           = 'ScourRSSBot';
	public const SEMRUSHBOT            = 'SemrushBot';
	public const SEMRUSHBOT_SI         = 'SemrushBot-SI';
	public const SERANKINGBACKLINKSBOT = 'SERankingBacklinksBot';
	public const SEZNAMBOT             = 'SeznamBot';
	public const SLACKBOT              = 'Slackbot';
	public const SMTBOT                = 'SMTBot';
	public const SPIDERLING            = 'SpiderLing';
	public const SURDOTLYBOT           = 'SurdotlyBot';
	public const TELEGRAMBOT           = 'TelegramBot';
	public const TWITTERBOT            = 'Twitterbot';
	public const WELLKNOWNBOT          = 'WellKnownBot';
	public const WGET                  = 'Wget';
	public const WORDPRESS             = 'WordPress';
	public const WPBOT                 = 'wpbot';
	public const YANDEXBOT             = 'YandexBot';
	public const YANDEXIMAGES          = 'YandexImages';
	public const YANDEXMOBILEBOT       = 'YandexMobileBot';
	public const YANDEXRCA             = 'YandexRCA';
	public const YANDEXUSERPROXY       = 'YandexUserproxy';
	public const YETI                  = 'Yeti';

}

