<?php

// DO NOT EDIT THIS FILE - IT IS GENERATED BY constant_generator.php

namespace donatj\UserAgent;

interface Browsers {

	public const ADSBOT_GOOGLE       = 'AdsBot-Google';
	public const ANDROID_BROWSER     = 'Android Browser';
	public const APPLEBOT            = 'Applebot';
	public const BAIDUSPIDER         = 'Baiduspider';
	public const BINGBOT             = 'bingbot';
	public const BLACKBERRY_BROWSER  = 'BlackBerry Browser';
	public const BROWSER             = 'Browser';
	public const BUNJALLOO           = 'Bunjalloo';
	public const CAMINO              = 'Camino';
	public const CHATGPT_USER        = 'ChatGPT-User';
	public const CHROME              = 'Chrome';
	public const CURL                = 'curl';
	public const EDGE                = 'Edge';
	public const FACEBOOKEXTERNALHIT = 'facebookexternalhit';
	public const FEEDVALIDATOR       = 'FeedValidator';
	public const FIREFOX             = 'Firefox';
	public const GOOGLEBOT           = 'Googlebot';
	public const GOOGLEBOT_IMAGE     = 'Googlebot-Image';
	public const GOOGLEBOT_VIDEO     = 'Googlebot-Video';
	public const GPTBOT              = 'GPTBot';
	public const HEADLESSCHROME      = 'HeadlessChrome';
	public const IEMOBILE            = 'IEMobile';
	public const IMESSAGEBOT         = 'iMessageBot';
	public const KINDLE              = 'Kindle';
	public const LYNX                = 'Lynx';
	public const MASTODON            = 'Mastodon';
	public const MIDORI              = 'Midori';
	public const MIUIBROWSER         = 'MiuiBrowser';
	public const MSIE                = 'MSIE';
	public const MSNBOT_MEDIA        = 'msnbot-media';
	public const NETFRONT            = 'NetFront';
	public const NINTENDOBROWSER     = 'NintendoBrowser';
	public const OAI_SEARCHBOT       = 'OAI-SearchBot';
	public const OCULUSBROWSER       = 'OculusBrowser';
	public const OPERA               = 'Opera';
	public const PUFFIN              = 'Puffin';
	public const SAFARI              = 'Safari';
	public const SAILFISHBROWSER     = 'SailfishBrowser';
	public const SAMSUNGBROWSER      = 'SamsungBrowser';
	public const SILK                = 'Silk';
	public const SLACKBOT            = 'Slackbot';
	public const TELEGRAMBOT         = 'TelegramBot';
	public const TIZENBROWSER        = 'TizenBrowser';
	public const TWITTERBOT          = 'Twitterbot';
	public const UC_BROWSER          = 'UC Browser';
	public const VALVE_STEAM_TENFOOT = 'Valve Steam Tenfoot';
	public const VIVALDI             = 'Vivaldi';
	public const WGET                = 'Wget';
	public const WHALE               = 'Whale';
	public const WORDPRESS           = 'WordPress';
	public const YANDEX              = 'Yandex';
	public const YANDEXBOT           = 'YandexBot';

}

