<?php

// DO NOT EDIT THIS FILE - IT IS GENERATED BY constant_generator.php

namespace donatj\UserAgent;

interface Platforms {

	public const MACINTOSH        = 'Macintosh';
	public const CHROME_OS        = 'Chrome OS';
	public const LINUX            = 'Linux';
	public const WINDOWS          = 'Windows';
	public const ANDROID          = 'Android';
	public const BLACKBERRY       = 'BlackBerry';
	public const FREEBSD          = 'FreeBSD';
	public const FUCHSIA          = 'Fuchsia';
	public const IPAD             = 'iPad';
	public const IPHONE           = 'iPhone';
	public const IPOD             = 'iPod';
	public const KINDLE           = 'Kindle';
	public const KINDLE_FIRE      = 'Kindle Fire';
	public const NETBSD           = 'NetBSD';
	public const NEW_NINTENDO_3DS = 'New Nintendo 3DS';
	public const NINTENDO_3DS     = 'Nintendo 3DS';
	public const NINTENDO_DS      = 'Nintendo DS';
	public const NINTENDO_SWITCH  = 'Nintendo Switch';
	public const NINTENDO_WII     = 'Nintendo Wii';
	public const NINTENDO_WIIU    = 'Nintendo WiiU';
	public const OPENBSD          = 'OpenBSD';
	public const PLAYBOOK         = 'PlayBook';
	public const PLAYSTATION_3    = 'PlayStation 3';
	public const PLAYSTATION_4    = 'PlayStation 4';
	public const PLAYSTATION_5    = 'PlayStation 5';
	public const PLAYSTATION_VITA = 'PlayStation Vita';
	public const SAILFISH         = 'Sailfish';
	public const SYMBIAN          = 'Symbian';
	public const TIZEN            = 'Tizen';
	public const WINDOWS_PHONE    = 'Windows Phone';
	public const XBOX             = 'Xbox';
	public const XBOX_ONE         = 'Xbox One';

}

