<?php

// DO NOT EDIT THIS FILE - IT IS GENERATED BY constant_generator.php

namespace donatj\UserAgentParser\Browser {

	const ADSBOT_GOOGLE       = 'AdsBot-Google';
	const ANDROID_BROWSER     = 'Android Browser';
	const BAIDUSPIDER         = 'Baiduspider';
	const BINGBOT             = 'bingbot';
	const BLACKBERRY_BROWSER  = 'BlackBerry Browser';
	const BROWSER             = 'Browser';
	const BUNJALLOO           = 'Bunjalloo';
	const CAMINO              = 'Camino';
	const CHROME              = 'Chrome';
	const CURL                = 'curl';
	const EDGE                = 'Edge';
	const FACEBOOKEXTERNALHIT = 'facebookexternalhit';
	const FEEDVALIDATOR       = 'FeedValidator';
	const FIREFOX             = 'Firefox';
	const GOOGLEBOT           = 'Googlebot';
	const GOOGLEBOT_IMAGE     = 'Googlebot-Image';
	const GOOGLEBOT_VIDEO     = 'Googlebot-Video';
	const HEADLESSCHROME      = 'HeadlessChrome';
	const IEMOBILE            = 'IEMobile';
	const KINDLE              = 'Kindle';
	const LYNX                = 'Lynx';
	const MIDORI              = 'Midori';
	const MSIE                = 'MSIE';
	const MSNBOT_MEDIA        = 'msnbot-media';
	const NETFRONT            = 'NetFront';
	const NINTENDOBROWSER     = 'NintendoBrowser';
	const OCULUSBROWSER       = 'OculusBrowser';
	const OPERA               = 'Opera';
	const PUFFIN              = 'Puffin';
	const SAFARI              = 'Safari';
	const SAMSUNGBROWSER      = 'SamsungBrowser';
	const SILK                = 'Silk';
	const TIZENBROWSER        = 'TizenBrowser';
	const UC_BROWSER          = 'UC Browser';
	const VALVE_STEAM_TENFOOT = 'Valve Steam Tenfoot';
	const VIVALDI             = 'Vivaldi';
	const WGET                = 'Wget';
	const WORDPRESS           = 'WordPress';
	const YANDEX              = 'Yandex';
	const YANDEXBOT           = 'YandexBot';
}

namespace donatj\UserAgentParser\Platform {

	const MACINTOSH        = 'Macintosh';
	const CHROME_OS        = 'Chrome OS';
	const LINUX            = 'Linux';
	const WINDOWS          = 'Windows';
	const ANDROID          = 'Android';
	const BLACKBERRY       = 'BlackBerry';
	const FREEBSD          = 'FreeBSD';
	const IPAD             = 'iPad';
	const IPHONE           = 'iPhone';
	const IPOD             = 'iPod';
	const KINDLE           = 'Kindle';
	const KINDLE_FIRE      = 'Kindle Fire';
	const NETBSD           = 'NetBSD';
	const NEW_NINTENDO_3DS = 'New Nintendo 3DS';
	const NINTENDO_3DS     = 'Nintendo 3DS';
	const NINTENDO_DS      = 'Nintendo DS';
	const NINTENDO_SWITCH  = 'Nintendo Switch';
	const NINTENDO_WII     = 'Nintendo Wii';
	const NINTENDO_WIIU    = 'Nintendo WiiU';
	const OPENBSD          = 'OpenBSD';
	const PLAYBOOK         = 'PlayBook';
	const PLAYSTATION_3    = 'PlayStation 3';
	const PLAYSTATION_4    = 'PlayStation 4';
	const PLAYSTATION_VITA = 'PlayStation Vita';
	const TIZEN            = 'Tizen';
	const WINDOWS_PHONE    = 'Windows Phone';
	const XBOX             = 'Xbox';
	const XBOX_ONE         = 'Xbox One';
}

